server:
  port: 8070
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
springdoc:
  swagger-ui:
    path: /docs

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/distribute?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  web:
    resources:
      static-locations: classpath:/resources/static

shiro:
  config:
    hashAlgorithmName: md5
    hashIterations: 1
    salt: shiro
    shiroSessionPrefix: session
    shiroSessionTimeout: 1800000
    shiroSessionValidationInterval: 60000
    shiroCachePrefix: shiro-cache
    shiroCacheExpireTime: 120000
    isLogInSeparately: true


mybatis-plus:
  mapper-locations: classpath*:/**/mapper/*Mapper.xml