server:
  port: 8070
  servlet:
    context-path: /api/v1

springdoc:
  swagger-ui:
    path: /docs

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/distribute?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
